version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: microservices-postgres-dev
    environment:
      POSTGRES_DB: microservices_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: trd123
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices-network

  redis:
    image: redis:7-alpine
    container_name: microservices-redis-dev
    ports:
      - "6380:6379"
    networks:
      - microservices-network

volumes:
  postgres_dev_data:

networks:
  microservices-network:
    driver: bridge