export const PageSize = 10;
export const DefaultPage = 1;
export const MaxPageSize = 100;
export const TokenExpiryTime = 86400; // 24 hours in seconds
export const TokenType = 'Bearer';
export const DefaultSortOrder = 'DESC';
export const MinPasswordLength = 8;
export const MaxPasswordLength = 128;
export const MaxNameLength = 100;
export const MaxEmailLength = 255;
export const MaxProductNameLength = 255;
export const MinOrderAmount = 0.01;
export const MaxOrderAmount = 999999.99;
export const DefaultCurrency = 'USD';
export const RateLimitWindow = 900000; // 15 minutes in milliseconds
export const RateLimitMaxRequests = 100;
export const DatabaseTimeout = 30000; // 30 seconds
export const CacheExpiryTime = 3600; // 1 hour in seconds