export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  USER = 'USER',
  GUEST = 'GUEST',
}

export enum Permission {
  CREATE_USER = 'CREATE_USER',
  READ_USER = 'READ_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  CREATE_ORDER = 'CREATE_ORDER',
  READ_ORDER = 'READ_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
  DELETE_ORDER = 'DELETE_ORDER',
  MANAGE_SYSTEM = 'MANAGE_SYSTEM',
  VIEW_ANALYTICS = 'VIEW_ANALYTICS',
  MANAGE_ROLES = 'MANAGE_ROLES',
  EXPORT_DATA = 'EXPORT_DATA',
}

export enum AccessLevel {
  PUBLIC = 'PUBLIC',
  AUTHENTICATED = 'AUTHENTICATED',
  AUTHORIZED = 'AUTHORIZED',
  ADMIN_ONLY = 'ADMIN_ONLY',
  SUPER_ADMIN_ONLY = 'SUPER_ADMIN_ONLY',
}

export enum ResourceType {
  USER = 'USER',
  ORDER = 'ORDER',
  PRODUCT = 'PRODUCT',
  PAYMENT = 'PAYMENT',
  SYSTEM = 'SYSTEM',
  ANALYTICS = 'ANALYTICS',
}